### ISSUE TITLE
Colors not matching the latest version ones

### ISSUE THREAD

**Issue by mnaser** [dgknca/tailwindcss-full-bleed#1]
It seems that we have to use things like `bleed-coolGray-100` instead of `bleed-grey-100`.

**Comment by dgknca** [comment]
`bleed-gray-100` should work. This plugin works with any valid tailwindcss color. Even with arbitrary values like `bleed-[#ff0000]`
https://github.com/dgknca/tailwindcss-full-bleed/blob/e4331b7fdd1b9a24fc56bf2fd3db9c1caf3976ae/src/index.test.js#L170

`grey` is not valid for both v2 and v3 https://tailwindcss.com/docs/upgrade-guide#renamed-gray-scales
